name: Docker Image CI
on:
  push:
    # branches:
    #   - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run optcd
        uses: Talank/optCD-demo@main
        with:
          yaml-file: .github/workflows/ci.yml

      - name: Process workflow file and commit changes
        id: commit_step
        run: |
          cat .github/workflows/modified.yml
          ls -l .github/workflows/
          git config user.email "actions@github.com"
          git config user.name "${{ github.actor }}"
          
          git add .github/workflows/modified.yml
          git commit --amend --no-edit
          commit_id=$(git rev-parse HEAD)
          echo "commit_id=$commit_id" >> $GITHUB_ENV
          # git push --force

      - name: Checkout to specific commit
        run: |
          git fetch
          git checkout ${{ env.commit_id }}

      # - name: Run modified workflow
      #   run: |
      #     gh workflow list
      #     gh workflow run modified.yml
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger modified workflow via GitHub API
        run: |
          git log
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref":"main"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/modified.yml/dispatches
